#路由规则
zuul:
  retryable: true
  add-host-header: true
  ignoredServices: "*"
  sensitiveHeaders: "*"
  routes:
    operation-application:
      path: /operation/**
      stripPrefix: false
    merchant-application:
      path: /merchant/**
      stripPrefix: false
    uaa-service: 
      path: /uaa/**
      stripPrefix: false
    transaction-service:
      path: /transaction/**
      stripPrefix: false

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 93000  # 设置熔断超时时间  default 1000
        timeout:
          enabled: true # 打开超时熔断功能 default true

ribbon:
  nacos:
    enabled: true # 不知道是否生效
  ConnectTimeout: 3000 # 设置连接超时时间 default 2000
  ReadTimeout: 20000    # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: false # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 1    # 切换实例的重试次数  default 1
  MaxAutoRetries: 1     # 对当前实例的重试次数 default 0