spring:
  redis:
    database: 0
    host: 192.168.249.150
    port: 6379
    timeout: 1000ms
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
      shutdown-timeout: 1000ms